// <auto-generated />
using System;
using ITIExaminationSyustem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITIExaminationSyustem.Migrations
{
    [DbContext(typeof(Exam_Context))]
    [Migration("20240305140740_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITIExaminationSyustem.Models.Department", b =>
                {
                    b.Property<int>("Department_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Department_Id"));

                    b.Property<int?>("Department_MgrId")
                        .HasColumnType("int");

                    b.Property<string>("Department_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Department_Id");

                    b.HasIndex("Department_MgrId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ITIExaminationSyustem.Models.DepartmentInstructors", b =>
                {
                    b.Property<int?>("Dept_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Ins_Id")
                        .HasColumnType("int");

                    b.HasKey("Dept_Id", "Ins_Id");

                    b.HasIndex("Ins_Id");

                    b.ToTable("DepartmentInstructors");
                });

            modelBuilder.Entity("ITIExaminationSyustem.Models.Instructor", b =>
                {
                    b.Property<int>("Instructor_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Instructor_Id"));

                    b.Property<string>("Instructor_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructor_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructor_Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Instructor_Id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("ITIExaminationSyustem.Models.Department", b =>
                {
                    b.HasOne("ITIExaminationSyustem.Models.Instructor", "Navigation_Department_Manager_Instructor")
                        .WithMany("Departments")
                        .HasForeignKey("Department_MgrId");

                    b.Navigation("Navigation_Department_Manager_Instructor");
                });

            modelBuilder.Entity("ITIExaminationSyustem.Models.DepartmentInstructors", b =>
                {
                    b.HasOne("ITIExaminationSyustem.Models.Department", "Navigation_Department")
                        .WithMany("Navigation_Department_Instructor")
                        .HasForeignKey("Dept_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITIExaminationSyustem.Models.Instructor", "Navigation_Instructor")
                        .WithMany("Navigation_Department_Instructor")
                        .HasForeignKey("Ins_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Navigation_Department");

                    b.Navigation("Navigation_Instructor");
                });

            modelBuilder.Entity("ITIExaminationSyustem.Models.Department", b =>
                {
                    b.Navigation("Navigation_Department_Instructor");
                });

            modelBuilder.Entity("ITIExaminationSyustem.Models.Instructor", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Navigation_Department_Instructor");
                });
#pragma warning restore 612, 618
        }
    }
}
